name: sign and release

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/manifest.json'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: Sign for Firefox
        run: web-ext sign --source-dir=src/ --artifacts-dir=/home/batuo/bbx/web-ext-artifacts --channel=unlisted

      - name: Add to the latest release
        run: python3 /home/batuo/bbx/update.py